version: '3'

services:
  psql:
    image: mdillon/postgis:10-alpine
    restart: on-failure
    env_file:
      - ./config/environments/psql-development.env
    ports:
      - 5432

  rails:
    build: .
    restart: on-failure
    entrypoint: rails
    command: server
    env_file:
      - ./config/environments/psql-development.env
    links:
      - psql
    ports:
      - 33000:3000